name: Build and Push
on:
  push: { branches: [main] }
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: cloudops-autopilot
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: AWS OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      - name: ECR Login
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and Push
        env:
          REGISTRY: ${{ steps.ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./app
          docker push $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
